/**
 * Zod schemas for the bookings module — read endpoints (Phase 1 scope).
 *
 * Write endpoints (POST / PUT / PATCH / DELETE) still live in the legacy
 * `controller/bookingController.js` and `routes/bookings.js`. They will
 * migrate in their own follow-up turn alongside the payment saga work.
 */
const { z } = require("zod");

const objectIdString = z.string().regex(/^[a-fA-F0-9]{24}$/, "Invalid id format");

// User id can either be a Mongo ObjectId string or a legacy non-ObjectId
// string (the audit found `bookingId` and friends generated by Math.random
// that aren't valid ObjectIds). The service handles both shapes.
const userIdParam = z.string().min(1).max(48);

// ─── GET /api/bookings?date=YYYY-MM-DD ──────────────────────────────────────
const listByDateQuery = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in YYYY-MM-DD format"),
});

// ─── GET /api/bookings/:id ──────────────────────────────────────────────────
const getByIdParams = z.object({ id: objectIdString });

// ─── GET /api/bookings/user/:userId ─────────────────────────────────────────
const listForUserParams = z.object({ userId: userIdParam });

module.exports = {
  listByDateQuery,
  getByIdParams,
  listForUserParams,
};
