/**
 * Zod schemas for the bookings module.
 *
 * All write endpoints whitelist their fields explicitly to kill the
 * mass-assignment risk that was in the legacy controller
 * (`Booking.create(req.body)`). Server-controlled fields (`bookingId`,
 * `confirmationSent`, `invoiceGenerated`, etc.) are deliberately absent —
 * clients cannot set them.
 */
const { z } = require("zod");

const objectIdString = z.string().regex(/^[a-fA-F0-9]{24}$/, "Invalid id format");

// User id can either be a Mongo ObjectId string or a legacy non-ObjectId
// string (the audit found `bookingId` and friends generated by Math.random
// that aren't valid ObjectIds). The service handles both shapes.
const userIdParam = z.string().min(1).max(48);

// Status values supported by the legacy controller.
const bookingStatus = z.enum([
  "pending",
  "confirmed",
  "checked-in",
  "checked-out",
  "cancelled",
  "active",
]);

const serviceModelEnum = z.enum(["Management", "Offer"]);
const serviceNameEnum = z.enum(["activity", "camper-van", "unique-stay"]);

const isoDate = z.union([z.iso.datetime(), z.iso.date()]);

// ─── Sub-schemas for nested objects on the Booking document ─────────────────
const extraItem = z.object({
  name: z.string().trim().min(1).max(120),
  price: z.number().nonnegative(),
  quantity: z.number().int().positive().default(1),
});

const paymentDetails = z.object({
  amount: z.number().nonnegative(),
  currency: z.string().trim().min(3).max(8).optional(),
  paymentMethod: z.enum([
    "credit_card",
    "debit_card",
    "paypal",
    "bank_transfer",
    "cash",
    "razorpay",
  ]),
  transactionId: z.string().trim().max(120).optional(),
  paymentStatus: z.enum(["pending", "completed", "failed", "refunded"]).optional(),
  paidAt: isoDate.optional(),
});

// ─── GET /api/bookings?date=YYYY-MM-DD ──────────────────────────────────────
const listByDateQuery = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in YYYY-MM-DD format"),
});

// ─── GET /api/bookings/:id ──────────────────────────────────────────────────
const getByIdParams = z.object({ id: objectIdString });

// ─── GET /api/bookings/user/:userId ─────────────────────────────────────────
const listForUserParams = z.object({ userId: userIdParam });

// ─── GET /api/bookings/legacy/all (admin filter view) ───────────────────────
const listForAdminQuery = z.object({
  tab: z
    .enum(["all-bookings", "upcoming-bookings", "past-booking", "cancelled-bookings"])
    .optional(),
  serviceType: z.enum(["caravan", "stay", "activity"]).optional(),
  search: z.string().trim().max(200).optional(),
  sortBy: z.string().trim().max(40).optional(),
  sortDir: z.enum(["asc", "desc"]).optional(),
});

// ─── POST /api/bookings ─────────────────────────────────────────────────────
// Strict whitelist. Fields the *server* controls are deliberately absent:
// bookingId, confirmationSent/At, invoiceGenerated, invoicePath, cancelledAt,
// createdAt, updatedAt, _id.
const createBookingBody = z.object({
  userId: objectIdString,
  serviceId: objectIdString,
  serviceModel: serviceModelEnum.optional(),
  serviceName: serviceNameEnum,
  clientName: z.string().trim().min(1).max(120),
  clientEmail: z
    .email()
    .trim()
    .max(254)
    .transform((s) => s.toLowerCase()),
  clientPhone: z.string().trim().max(40).optional(),
  checkInDate: isoDate,
  checkOutDate: isoDate,
  numberOfGuests: z.number().int().positive().max(100),
  location: z.string().trim().max(200).optional(),
  pickupLocation: z.string().trim().max(200).optional(),
  totalAmount: z.number().nonnegative(),
  baseAmount: z.number().nonnegative(),
  extraItems: z.array(extraItem).optional(),
  paymentDetails: paymentDetails.optional(),
  bookingStatus: bookingStatus.optional(),
  specialRequests: z.string().trim().max(2000).optional(),
});

// ─── PUT /api/bookings/:id ──────────────────────────────────────────────────
// Same shape as create but every field optional. Reject empty-body updates.
const updateBookingParams = z.object({ id: objectIdString });
const updateBookingBody = createBookingBody
  .partial()
  .refine((data) => Object.keys(data).length > 0, {
    message: "At least one field must be provided",
  });

// ─── DELETE /api/bookings/:id ───────────────────────────────────────────────
const deleteBookingParams = z.object({ id: objectIdString });

// ─── PATCH /api/bookings/:id/status ─────────────────────────────────────────
const updateStatusParams = z.object({ id: objectIdString });
const updateStatusBody = z.object({ status: bookingStatus });

// ─── PATCH /api/bookings/:id/dates ──────────────────────────────────────────
const updateDatesParams = z.object({ id: objectIdString });
const updateDatesBody = z
  .object({
    startDate: isoDate.optional(),
    endDate: isoDate.optional(),
    action: z.string().trim().max(40).optional(),
  })
  .refine((data) => !!data.startDate || !!data.endDate, {
    message: "startDate or endDate is required",
  });

// ─── POST /api/bookings/:id/invoice ─────────────────────────────────────────
const invoiceParams = z.object({ id: objectIdString });

module.exports = {
  listByDateQuery,
  getByIdParams,
  listForUserParams,
  listForAdminQuery,
  createBookingBody,
  updateBookingParams,
  updateBookingBody,
  deleteBookingParams,
  updateStatusParams,
  updateStatusBody,
  updateDatesParams,
  updateDatesBody,
  invoiceParams,
};
