// GENERATED by scripts/build-location-data.mjs — do not edit by hand.
// Run `npm run build:locations` to regenerate from data/countries_states_cities.json.
//
// Bundled (not fetched) so country dropdowns and the phone dial-code picker
// render synchronously. States and cities are NOT here — they are fetched per
// country from /locations/<ISO2>.json by useCountriesData().

export interface CountryEntry {
  /** Display name, e.g. "India". Also the key every form stores. */
  name: string;
  /** ISO 3166-1 alpha-2, e.g. "IN". Used to locate /locations/<ISO2>.json. */
  iso2: string;
  /** International dialling prefix without "+", e.g. "91". */
  phonecode: string;
}

export const COUNTRIES: readonly CountryEntry[] = [
  {
    "name": "Afghanistan",
    "iso2": "AF",
    "phonecode": "93"
  },
  {
    "name": "Aland Islands",
    "iso2": "AX",
    "phonecode": "358"
  },
  {
    "name": "Albania",
    "iso2": "AL",
    "phonecode": "355"
  },
  {
    "name": "Algeria",
    "iso2": "DZ",
    "phonecode": "213"
  },
  {
    "name": "American Samoa",
    "iso2": "AS",
    "phonecode": "1"
  },
  {
    "name": "Andorra",
    "iso2": "AD",
    "phonecode": "376"
  },
  {
    "name": "Angola",
    "iso2": "AO",
    "phonecode": "244"
  },
  {
    "name": "Anguilla",
    "iso2": "AI",
    "phonecode": "1"
  },
  {
    "name": "Antarctica",
    "iso2": "AQ",
    "phonecode": "672"
  },
  {
    "name": "Antigua and Barbuda",
    "iso2": "AG",
    "phonecode": "1"
  },
  {
    "name": "Argentina",
    "iso2": "AR",
    "phonecode": "54"
  },
  {
    "name": "Armenia",
    "iso2": "AM",
    "phonecode": "374"
  },
  {
    "name": "Aruba",
    "iso2": "AW",
    "phonecode": "297"
  },
  {
    "name": "Australia",
    "iso2": "AU",
    "phonecode": "61"
  },
  {
    "name": "Austria",
    "iso2": "AT",
    "phonecode": "43"
  },
  {
    "name": "Azerbaijan",
    "iso2": "AZ",
    "phonecode": "994"
  },
  {
    "name": "Bahrain",
    "iso2": "BH",
    "phonecode": "973"
  },
  {
    "name": "Bangladesh",
    "iso2": "BD",
    "phonecode": "880"
  },
  {
    "name": "Barbados",
    "iso2": "BB",
    "phonecode": "1"
  },
  {
    "name": "Belarus",
    "iso2": "BY",
    "phonecode": "375"
  },
  {
    "name": "Belgium",
    "iso2": "BE",
    "phonecode": "32"
  },
  {
    "name": "Belize",
    "iso2": "BZ",
    "phonecode": "501"
  },
  {
    "name": "Benin",
    "iso2": "BJ",
    "phonecode": "229"
  },
  {
    "name": "Bermuda",
    "iso2": "BM",
    "phonecode": "1"
  },
  {
    "name": "Bhutan",
    "iso2": "BT",
    "phonecode": "975"
  },
  {
    "name": "Bolivia",
    "iso2": "BO",
    "phonecode": "591"
  },
  {
    "name": "Bonaire, Sint Eustatius and Saba",
    "iso2": "BQ",
    "phonecode": "599"
  },
  {
    "name": "Bosnia and Herzegovina",
    "iso2": "BA",
    "phonecode": "387"
  },
  {
    "name": "Botswana",
    "iso2": "BW",
    "phonecode": "267"
  },
  {
    "name": "Bouvet Island",
    "iso2": "BV",
    "phonecode": "0055"
  },
  {
    "name": "Brazil",
    "iso2": "BR",
    "phonecode": "55"
  },
  {
    "name": "British Indian Ocean Territory",
    "iso2": "IO",
    "phonecode": "246"
  },
  {
    "name": "Brunei",
    "iso2": "BN",
    "phonecode": "673"
  },
  {
    "name": "Bulgaria",
    "iso2": "BG",
    "phonecode": "359"
  },
  {
    "name": "Burkina Faso",
    "iso2": "BF",
    "phonecode": "226"
  },
  {
    "name": "Burundi",
    "iso2": "BI",
    "phonecode": "257"
  },
  {
    "name": "Cambodia",
    "iso2": "KH",
    "phonecode": "855"
  },
  {
    "name": "Cameroon",
    "iso2": "CM",
    "phonecode": "237"
  },
  {
    "name": "Canada",
    "iso2": "CA",
    "phonecode": "1"
  },
  {
    "name": "Cape Verde",
    "iso2": "CV",
    "phonecode": "238"
  },
  {
    "name": "Cayman Islands",
    "iso2": "KY",
    "phonecode": "1"
  },
  {
    "name": "Central African Republic",
    "iso2": "CF",
    "phonecode": "236"
  },
  {
    "name": "Chad",
    "iso2": "TD",
    "phonecode": "235"
  },
  {
    "name": "Chile",
    "iso2": "CL",
    "phonecode": "56"
  },
  {
    "name": "China",
    "iso2": "CN",
    "phonecode": "86"
  },
  {
    "name": "Christmas Island",
    "iso2": "CX",
    "phonecode": "61"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "iso2": "CC",
    "phonecode": "61"
  },
  {
    "name": "Colombia",
    "iso2": "CO",
    "phonecode": "57"
  },
  {
    "name": "Comoros",
    "iso2": "KM",
    "phonecode": "269"
  },
  {
    "name": "Congo",
    "iso2": "CG",
    "phonecode": "242"
  },
  {
    "name": "Cook Islands",
    "iso2": "CK",
    "phonecode": "682"
  },
  {
    "name": "Costa Rica",
    "iso2": "CR",
    "phonecode": "506"
  },
  {
    "name": "Cote D'Ivoire (Ivory Coast)",
    "iso2": "CI",
    "phonecode": "225"
  },
  {
    "name": "Croatia",
    "iso2": "HR",
    "phonecode": "385"
  },
  {
    "name": "Cuba",
    "iso2": "CU",
    "phonecode": "53"
  },
  {
    "name": "Curaçao",
    "iso2": "CW",
    "phonecode": "599"
  },
  {
    "name": "Cyprus",
    "iso2": "CY",
    "phonecode": "357"
  },
  {
    "name": "Czech Republic",
    "iso2": "CZ",
    "phonecode": "420"
  },
  {
    "name": "Democratic Republic of the Congo",
    "iso2": "CD",
    "phonecode": "243"
  },
  {
    "name": "Denmark",
    "iso2": "DK",
    "phonecode": "45"
  },
  {
    "name": "Djibouti",
    "iso2": "DJ",
    "phonecode": "253"
  },
  {
    "name": "Dominica",
    "iso2": "DM",
    "phonecode": "1"
  },
  {
    "name": "Dominican Republic",
    "iso2": "DO",
    "phonecode": "1"
  },
  {
    "name": "Ecuador",
    "iso2": "EC",
    "phonecode": "593"
  },
  {
    "name": "Egypt",
    "iso2": "EG",
    "phonecode": "20"
  },
  {
    "name": "El Salvador",
    "iso2": "SV",
    "phonecode": "503"
  },
  {
    "name": "Equatorial Guinea",
    "iso2": "GQ",
    "phonecode": "240"
  },
  {
    "name": "Eritrea",
    "iso2": "ER",
    "phonecode": "291"
  },
  {
    "name": "Estonia",
    "iso2": "EE",
    "phonecode": "372"
  },
  {
    "name": "Eswatini",
    "iso2": "SZ",
    "phonecode": "268"
  },
  {
    "name": "Ethiopia",
    "iso2": "ET",
    "phonecode": "251"
  },
  {
    "name": "Falkland Islands",
    "iso2": "FK",
    "phonecode": "500"
  },
  {
    "name": "Faroe Islands",
    "iso2": "FO",
    "phonecode": "298"
  },
  {
    "name": "Fiji Islands",
    "iso2": "FJ",
    "phonecode": "679"
  },
  {
    "name": "Finland",
    "iso2": "FI",
    "phonecode": "358"
  },
  {
    "name": "France",
    "iso2": "FR",
    "phonecode": "33"
  },
  {
    "name": "French Guiana",
    "iso2": "GF",
    "phonecode": "594"
  },
  {
    "name": "French Polynesia",
    "iso2": "PF",
    "phonecode": "689"
  },
  {
    "name": "French Southern Territories",
    "iso2": "TF",
    "phonecode": "262"
  },
  {
    "name": "Gabon",
    "iso2": "GA",
    "phonecode": "241"
  },
  {
    "name": "Georgia",
    "iso2": "GE",
    "phonecode": "995"
  },
  {
    "name": "Germany",
    "iso2": "DE",
    "phonecode": "49"
  },
  {
    "name": "Ghana",
    "iso2": "GH",
    "phonecode": "233"
  },
  {
    "name": "Gibraltar",
    "iso2": "GI",
    "phonecode": "350"
  },
  {
    "name": "Greece",
    "iso2": "GR",
    "phonecode": "30"
  },
  {
    "name": "Greenland",
    "iso2": "GL",
    "phonecode": "299"
  },
  {
    "name": "Grenada",
    "iso2": "GD",
    "phonecode": "1"
  },
  {
    "name": "Guadeloupe",
    "iso2": "GP",
    "phonecode": "590"
  },
  {
    "name": "Guam",
    "iso2": "GU",
    "phonecode": "1"
  },
  {
    "name": "Guatemala",
    "iso2": "GT",
    "phonecode": "502"
  },
  {
    "name": "Guernsey",
    "iso2": "GG",
    "phonecode": "44"
  },
  {
    "name": "Guinea",
    "iso2": "GN",
    "phonecode": "224"
  },
  {
    "name": "Guinea-Bissau",
    "iso2": "GW",
    "phonecode": "245"
  },
  {
    "name": "Guyana",
    "iso2": "GY",
    "phonecode": "592"
  },
  {
    "name": "Haiti",
    "iso2": "HT",
    "phonecode": "509"
  },
  {
    "name": "Heard Island and McDonald Islands",
    "iso2": "HM",
    "phonecode": "672"
  },
  {
    "name": "Honduras",
    "iso2": "HN",
    "phonecode": "504"
  },
  {
    "name": "Hong Kong S.A.R.",
    "iso2": "HK",
    "phonecode": "852"
  },
  {
    "name": "Hungary",
    "iso2": "HU",
    "phonecode": "36"
  },
  {
    "name": "Iceland",
    "iso2": "IS",
    "phonecode": "354"
  },
  {
    "name": "India",
    "iso2": "IN",
    "phonecode": "91"
  },
  {
    "name": "Indonesia",
    "iso2": "ID",
    "phonecode": "62"
  },
  {
    "name": "Iran",
    "iso2": "IR",
    "phonecode": "98"
  },
  {
    "name": "Iraq",
    "iso2": "IQ",
    "phonecode": "964"
  },
  {
    "name": "Ireland",
    "iso2": "IE",
    "phonecode": "353"
  },
  {
    "name": "Israel",
    "iso2": "IL",
    "phonecode": "972"
  },
  {
    "name": "Italy",
    "iso2": "IT",
    "phonecode": "39"
  },
  {
    "name": "Jamaica",
    "iso2": "JM",
    "phonecode": "1"
  },
  {
    "name": "Japan",
    "iso2": "JP",
    "phonecode": "81"
  },
  {
    "name": "Jersey",
    "iso2": "JE",
    "phonecode": "44"
  },
  {
    "name": "Jordan",
    "iso2": "JO",
    "phonecode": "962"
  },
  {
    "name": "Kazakhstan",
    "iso2": "KZ",
    "phonecode": "7"
  },
  {
    "name": "Kenya",
    "iso2": "KE",
    "phonecode": "254"
  },
  {
    "name": "Kiribati",
    "iso2": "KI",
    "phonecode": "686"
  },
  {
    "name": "Kosovo",
    "iso2": "XK",
    "phonecode": "383"
  },
  {
    "name": "Kuwait",
    "iso2": "KW",
    "phonecode": "965"
  },
  {
    "name": "Kyrgyzstan",
    "iso2": "KG",
    "phonecode": "996"
  },
  {
    "name": "Laos",
    "iso2": "LA",
    "phonecode": "856"
  },
  {
    "name": "Latvia",
    "iso2": "LV",
    "phonecode": "371"
  },
  {
    "name": "Lebanon",
    "iso2": "LB",
    "phonecode": "961"
  },
  {
    "name": "Lesotho",
    "iso2": "LS",
    "phonecode": "266"
  },
  {
    "name": "Liberia",
    "iso2": "LR",
    "phonecode": "231"
  },
  {
    "name": "Libya",
    "iso2": "LY",
    "phonecode": "218"
  },
  {
    "name": "Liechtenstein",
    "iso2": "LI",
    "phonecode": "423"
  },
  {
    "name": "Lithuania",
    "iso2": "LT",
    "phonecode": "370"
  },
  {
    "name": "Luxembourg",
    "iso2": "LU",
    "phonecode": "352"
  },
  {
    "name": "Macau S.A.R.",
    "iso2": "MO",
    "phonecode": "853"
  },
  {
    "name": "Madagascar",
    "iso2": "MG",
    "phonecode": "261"
  },
  {
    "name": "Malawi",
    "iso2": "MW",
    "phonecode": "265"
  },
  {
    "name": "Malaysia",
    "iso2": "MY",
    "phonecode": "60"
  },
  {
    "name": "Maldives",
    "iso2": "MV",
    "phonecode": "960"
  },
  {
    "name": "Mali",
    "iso2": "ML",
    "phonecode": "223"
  },
  {
    "name": "Malta",
    "iso2": "MT",
    "phonecode": "356"
  },
  {
    "name": "Man (Isle of)",
    "iso2": "IM",
    "phonecode": "44"
  },
  {
    "name": "Marshall Islands",
    "iso2": "MH",
    "phonecode": "692"
  },
  {
    "name": "Martinique",
    "iso2": "MQ",
    "phonecode": "596"
  },
  {
    "name": "Mauritania",
    "iso2": "MR",
    "phonecode": "222"
  },
  {
    "name": "Mauritius",
    "iso2": "MU",
    "phonecode": "230"
  },
  {
    "name": "Mayotte",
    "iso2": "YT",
    "phonecode": "262"
  },
  {
    "name": "Mexico",
    "iso2": "MX",
    "phonecode": "52"
  },
  {
    "name": "Micronesia",
    "iso2": "FM",
    "phonecode": "691"
  },
  {
    "name": "Moldova",
    "iso2": "MD",
    "phonecode": "373"
  },
  {
    "name": "Monaco",
    "iso2": "MC",
    "phonecode": "377"
  },
  {
    "name": "Mongolia",
    "iso2": "MN",
    "phonecode": "976"
  },
  {
    "name": "Montenegro",
    "iso2": "ME",
    "phonecode": "382"
  },
  {
    "name": "Montserrat",
    "iso2": "MS",
    "phonecode": "1"
  },
  {
    "name": "Morocco",
    "iso2": "MA",
    "phonecode": "212"
  },
  {
    "name": "Mozambique",
    "iso2": "MZ",
    "phonecode": "258"
  },
  {
    "name": "Myanmar",
    "iso2": "MM",
    "phonecode": "95"
  },
  {
    "name": "Namibia",
    "iso2": "NA",
    "phonecode": "264"
  },
  {
    "name": "Nauru",
    "iso2": "NR",
    "phonecode": "674"
  },
  {
    "name": "Nepal",
    "iso2": "NP",
    "phonecode": "977"
  },
  {
    "name": "Netherlands",
    "iso2": "NL",
    "phonecode": "31"
  },
  {
    "name": "New Caledonia",
    "iso2": "NC",
    "phonecode": "687"
  },
  {
    "name": "New Zealand",
    "iso2": "NZ",
    "phonecode": "64"
  },
  {
    "name": "Nicaragua",
    "iso2": "NI",
    "phonecode": "505"
  },
  {
    "name": "Niger",
    "iso2": "NE",
    "phonecode": "227"
  },
  {
    "name": "Nigeria",
    "iso2": "NG",
    "phonecode": "234"
  },
  {
    "name": "Niue",
    "iso2": "NU",
    "phonecode": "683"
  },
  {
    "name": "Norfolk Island",
    "iso2": "NF",
    "phonecode": "672"
  },
  {
    "name": "North Korea",
    "iso2": "KP",
    "phonecode": "850"
  },
  {
    "name": "North Macedonia",
    "iso2": "MK",
    "phonecode": "389"
  },
  {
    "name": "Northern Mariana Islands",
    "iso2": "MP",
    "phonecode": "1"
  },
  {
    "name": "Norway",
    "iso2": "NO",
    "phonecode": "47"
  },
  {
    "name": "Oman",
    "iso2": "OM",
    "phonecode": "968"
  },
  {
    "name": "Pakistan",
    "iso2": "PK",
    "phonecode": "92"
  },
  {
    "name": "Palau",
    "iso2": "PW",
    "phonecode": "680"
  },
  {
    "name": "Palestinian Territory Occupied",
    "iso2": "PS",
    "phonecode": "970"
  },
  {
    "name": "Panama",
    "iso2": "PA",
    "phonecode": "507"
  },
  {
    "name": "Papua New Guinea",
    "iso2": "PG",
    "phonecode": "675"
  },
  {
    "name": "Paraguay",
    "iso2": "PY",
    "phonecode": "595"
  },
  {
    "name": "Peru",
    "iso2": "PE",
    "phonecode": "51"
  },
  {
    "name": "Philippines",
    "iso2": "PH",
    "phonecode": "63"
  },
  {
    "name": "Pitcairn Island",
    "iso2": "PN",
    "phonecode": "870"
  },
  {
    "name": "Poland",
    "iso2": "PL",
    "phonecode": "48"
  },
  {
    "name": "Portugal",
    "iso2": "PT",
    "phonecode": "351"
  },
  {
    "name": "Puerto Rico",
    "iso2": "PR",
    "phonecode": "1"
  },
  {
    "name": "Qatar",
    "iso2": "QA",
    "phonecode": "974"
  },
  {
    "name": "Reunion",
    "iso2": "RE",
    "phonecode": "262"
  },
  {
    "name": "Romania",
    "iso2": "RO",
    "phonecode": "40"
  },
  {
    "name": "Russia",
    "iso2": "RU",
    "phonecode": "7"
  },
  {
    "name": "Rwanda",
    "iso2": "RW",
    "phonecode": "250"
  },
  {
    "name": "Saint Helena",
    "iso2": "SH",
    "phonecode": "290"
  },
  {
    "name": "Saint Kitts and Nevis",
    "iso2": "KN",
    "phonecode": "1"
  },
  {
    "name": "Saint Lucia",
    "iso2": "LC",
    "phonecode": "1"
  },
  {
    "name": "Saint Pierre and Miquelon",
    "iso2": "PM",
    "phonecode": "508"
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "iso2": "VC",
    "phonecode": "1"
  },
  {
    "name": "Saint-Barthelemy",
    "iso2": "BL",
    "phonecode": "590"
  },
  {
    "name": "Saint-Martin (French part)",
    "iso2": "MF",
    "phonecode": "590"
  },
  {
    "name": "Samoa",
    "iso2": "WS",
    "phonecode": "685"
  },
  {
    "name": "San Marino",
    "iso2": "SM",
    "phonecode": "378"
  },
  {
    "name": "Sao Tome and Principe",
    "iso2": "ST",
    "phonecode": "239"
  },
  {
    "name": "Saudi Arabia",
    "iso2": "SA",
    "phonecode": "966"
  },
  {
    "name": "Senegal",
    "iso2": "SN",
    "phonecode": "221"
  },
  {
    "name": "Serbia",
    "iso2": "RS",
    "phonecode": "381"
  },
  {
    "name": "Seychelles",
    "iso2": "SC",
    "phonecode": "248"
  },
  {
    "name": "Sierra Leone",
    "iso2": "SL",
    "phonecode": "232"
  },
  {
    "name": "Singapore",
    "iso2": "SG",
    "phonecode": "65"
  },
  {
    "name": "Sint Maarten (Dutch part)",
    "iso2": "SX",
    "phonecode": "1721"
  },
  {
    "name": "Slovakia",
    "iso2": "SK",
    "phonecode": "421"
  },
  {
    "name": "Slovenia",
    "iso2": "SI",
    "phonecode": "386"
  },
  {
    "name": "Solomon Islands",
    "iso2": "SB",
    "phonecode": "677"
  },
  {
    "name": "Somalia",
    "iso2": "SO",
    "phonecode": "252"
  },
  {
    "name": "South Africa",
    "iso2": "ZA",
    "phonecode": "27"
  },
  {
    "name": "South Georgia",
    "iso2": "GS",
    "phonecode": "500"
  },
  {
    "name": "South Korea",
    "iso2": "KR",
    "phonecode": "82"
  },
  {
    "name": "South Sudan",
    "iso2": "SS",
    "phonecode": "211"
  },
  {
    "name": "Spain",
    "iso2": "ES",
    "phonecode": "34"
  },
  {
    "name": "Sri Lanka",
    "iso2": "LK",
    "phonecode": "94"
  },
  {
    "name": "Sudan",
    "iso2": "SD",
    "phonecode": "249"
  },
  {
    "name": "Suriname",
    "iso2": "SR",
    "phonecode": "597"
  },
  {
    "name": "Svalbard and Jan Mayen Islands",
    "iso2": "SJ",
    "phonecode": "47"
  },
  {
    "name": "Sweden",
    "iso2": "SE",
    "phonecode": "46"
  },
  {
    "name": "Switzerland",
    "iso2": "CH",
    "phonecode": "41"
  },
  {
    "name": "Syria",
    "iso2": "SY",
    "phonecode": "963"
  },
  {
    "name": "Taiwan",
    "iso2": "TW",
    "phonecode": "886"
  },
  {
    "name": "Tajikistan",
    "iso2": "TJ",
    "phonecode": "992"
  },
  {
    "name": "Tanzania",
    "iso2": "TZ",
    "phonecode": "255"
  },
  {
    "name": "Thailand",
    "iso2": "TH",
    "phonecode": "66"
  },
  {
    "name": "The Bahamas",
    "iso2": "BS",
    "phonecode": "1"
  },
  {
    "name": "The Gambia ",
    "iso2": "GM",
    "phonecode": "220"
  },
  {
    "name": "Timor-Leste",
    "iso2": "TL",
    "phonecode": "670"
  },
  {
    "name": "Togo",
    "iso2": "TG",
    "phonecode": "228"
  },
  {
    "name": "Tokelau",
    "iso2": "TK",
    "phonecode": "690"
  },
  {
    "name": "Tonga",
    "iso2": "TO",
    "phonecode": "676"
  },
  {
    "name": "Trinidad and Tobago",
    "iso2": "TT",
    "phonecode": "1"
  },
  {
    "name": "Tunisia",
    "iso2": "TN",
    "phonecode": "216"
  },
  {
    "name": "Turkey",
    "iso2": "TR",
    "phonecode": "90"
  },
  {
    "name": "Turkmenistan",
    "iso2": "TM",
    "phonecode": "993"
  },
  {
    "name": "Turks and Caicos Islands",
    "iso2": "TC",
    "phonecode": "1"
  },
  {
    "name": "Tuvalu",
    "iso2": "TV",
    "phonecode": "688"
  },
  {
    "name": "Uganda",
    "iso2": "UG",
    "phonecode": "256"
  },
  {
    "name": "Ukraine",
    "iso2": "UA",
    "phonecode": "380"
  },
  {
    "name": "United Arab Emirates",
    "iso2": "AE",
    "phonecode": "971"
  },
  {
    "name": "United Kingdom",
    "iso2": "GB",
    "phonecode": "44"
  },
  {
    "name": "United States",
    "iso2": "US",
    "phonecode": "1"
  },
  {
    "name": "United States Minor Outlying Islands",
    "iso2": "UM",
    "phonecode": "1"
  },
  {
    "name": "Uruguay",
    "iso2": "UY",
    "phonecode": "598"
  },
  {
    "name": "Uzbekistan",
    "iso2": "UZ",
    "phonecode": "998"
  },
  {
    "name": "Vanuatu",
    "iso2": "VU",
    "phonecode": "678"
  },
  {
    "name": "Vatican City State (Holy See)",
    "iso2": "VA",
    "phonecode": "379"
  },
  {
    "name": "Venezuela",
    "iso2": "VE",
    "phonecode": "58"
  },
  {
    "name": "Vietnam",
    "iso2": "VN",
    "phonecode": "84"
  },
  {
    "name": "Virgin Islands (British)",
    "iso2": "VG",
    "phonecode": "1"
  },
  {
    "name": "Virgin Islands (US)",
    "iso2": "VI",
    "phonecode": "1"
  },
  {
    "name": "Wallis and Futuna Islands",
    "iso2": "WF",
    "phonecode": "681"
  },
  {
    "name": "Western Sahara",
    "iso2": "EH",
    "phonecode": "212"
  },
  {
    "name": "Yemen",
    "iso2": "YE",
    "phonecode": "967"
  },
  {
    "name": "Zambia",
    "iso2": "ZM",
    "phonecode": "260"
  },
  {
    "name": "Zimbabwe",
    "iso2": "ZW",
    "phonecode": "263"
  }
];

/** Look up a country by its display name (the value forms persist). */
export const countryByName = (name?: string | null): CountryEntry | undefined =>
  name ? COUNTRIES.find((c) => c.name === name) : undefined;
