import { useMemo } from "react";
import { useQueries } from "@tanstack/react-query";

import { COUNTRIES, countryByName, type CountryEntry } from "@/data/countries";

/**
 * Country / state / city data for the location pickers.
 *
 * This used to fetch `/countries_states_cities.json` — a single 36.8 MB file
 * (3.5 MB gzipped) pulled in by 8 pages including register and checkout, just to
 * read one country's state list. `JSON.parse` on it blocked the main thread for
 * seconds and spiked the JS heap by hundreds of MB.
 *
 * Now the country list is bundled (see data/countries.ts, generated by
 * scripts/build-location-data.mjs) and each country's states/cities are fetched
 * on demand from `/locations/<ISO2>.json`. India is 20 KB gzipped.
 *
 * The returned array keeps the ORIGINAL shape on purpose — every existing call
 * site does:
 *
 *     locationData.find((c) => c.name === someCountry)?.states
 *       ?.find((s) => s.name === someState)?.cities?.map((city) => city.name)
 *
 * and continues to work untouched. Countries whose detail hasn't been requested
 * (or hasn't arrived yet) simply have no `states` key, which those `?.` chains
 * already handle by rendering an empty option list.
 *
 * Pass the country name(s) whose states you actually need:
 *
 *     const locationData = useCountriesData(formData.locality);           // one
 *     const locationData = useCountriesData([businessCountry, homeCountry]); // several
 *     const locationData = useCountriesData();                            // India
 */

export interface CityEntry {
  name: string;
}
export interface StateEntry {
  name: string;
  cities: CityEntry[];
}
export interface CountryWithStates extends CountryEntry {
  states?: StateEntry[];
}

interface CountryDetail extends CountryEntry {
  states: StateEntry[];
}

const DEFAULT_COUNTRY = "India";

async function fetchCountryDetail(iso2: string): Promise<CountryDetail | null> {
  try {
    const res = await fetch(`/locations/${iso2}.json`);
    if (!res.ok) return null;
    return (await res.json()) as CountryDetail;
  } catch {
    // A missing/unreachable location file must not break the form — the state
    // and city dropdowns just stay empty, same as the old failure mode.
    return null;
  }
}

export function useCountriesData(countryNames?: string | string[]): CountryWithStates[] {
  // Normalise to a stable, de-duplicated list of ISO2 codes. Joining into a
  // string keeps the memo/query keys stable across renders that pass a new
  // array literal with the same contents.
  const isoKey = useMemo(() => {
    const names = (
      Array.isArray(countryNames) ? countryNames : [countryNames ?? DEFAULT_COUNTRY]
    ).filter((n): n is string => !!n && typeof n === "string");

    const codes = new Set<string>();
    for (const name of names.length ? names : [DEFAULT_COUNTRY]) {
      const iso2 = countryByName(name)?.iso2;
      if (iso2) codes.add(iso2);
    }
    return [...codes].sort().join(",");
  }, [Array.isArray(countryNames) ? countryNames.join("|") : countryNames]);

  const isoCodes = useMemo(() => (isoKey ? isoKey.split(",") : []), [isoKey]);

  const results = useQueries({
    queries: isoCodes.map((iso2) => ({
      queryKey: ["locations", iso2],
      queryFn: () => fetchCountryDetail(iso2),
      staleTime: Infinity, // static asset
      gcTime: Infinity,
    })),
  });

  // `results` is a new array identity every render, so key the merge on the
  // loaded payloads rather than on `results` itself — otherwise every consumer
  // would see a fresh array and re-render on any unrelated state change.
  const loadedKey = results.map((r) => (r.data ? r.data.iso2 : "")).join(",");

  return useMemo(() => {
    const byIso = new Map<string, StateEntry[]>();
    for (const r of results) {
      if (r.data?.iso2) byIso.set(r.data.iso2, r.data.states || []);
    }
    if (!byIso.size) return COUNTRIES as CountryWithStates[];

    return COUNTRIES.map((c) => {
      const states = byIso.get(c.iso2);
      return states ? { ...c, states } : c;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadedKey]);
}

export default useCountriesData;
